# Kafka UI (https://github.com/provectus/kafka-ui)
kafka-ui:
  # This annotation forces a rolling update when the env vars change.
  podAnnotations:
    checksum/config: "{{ toYaml .Values.kafka-ui.envVars | sha256sum }}"

  envVars:
    - name: KAFKA_CLUSTERS_0_NAME
      value: "Kafka Cluster"
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: "{{ .Release.Name }}-kafka:9092"

  # Service is ClusterIP by default, not exposed externally
  service:
    type: ClusterIP