kafka:
  kraft:
    enabled: true
  broker:
    replicaCount: 2
    persistence:
      enabled: false
  controller:
    replicaCount: 1
    persistence:
      enabled: false
    livenessProbe:
      initialDelaySeconds: 120
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

  externalAccess:
    enabled: true
    broker:
      service:
        type: NodePort
        nodePorts:
          - 32092
          - 32093
        externalIPs:
          - 34.47.88.194
          - 34.47.88.194
    controller:
      service:
        type: ClusterIP

kafka-ui:
  env:
    KAFKA_CLUSTERS_0_NAME: "Development Kafka"
    KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "{{ .Release.Name }}-kafka:9092"
  service:
    type: NodePort
    port: 8080
    nodePort: 30000
