kafka:
  broker:
    replicaCount: 2
    persistence:
      enabled: false
  controller:
    replicaCount: 1
    persistence:
      enabled: false
    livenessProbe:
      initialDelaySeconds: 120
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

  listeners:
    client:
      protocol: PLAINTEXT
      port: 9092
    external:
      protocol: PLAINTEXT
      port: 9093

  advertisedListeners:
    client: "{{ .Release.Name }}:9092"
    external:
      - 34.47.88.194:32092
      - 34.47.88.194:32093

  external:
    enabled: true
    service:
      type: NodePort
      ports:
        external: 9093
      nodePorts:
        external:
          - 32092
          - 32093

kafka-ui:
  envVars:
    - name: KAFKA_CLUSTERS_0_NAME
      value: "Development Kafka"
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: "{{ .Release.Name }}:9092"
  service:
    type: NodePort
    nodePort: 30000
