# Production specific values
kafka:
  broker:
    replicaCount: 3
  controller:
    replicaCount: 3

  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 2
      memory: 4Gi
