kafka:
  kraft:
    enabled: true
  broker:
    replicaCount: 2
  controller:
    replicaCount: 1
    livenessProbe:
      initialDelaySeconds: 120
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

  externalAccess:
    enabled: true
    broker:
      service:
        type: NodePort
        nodePorts:
          - 32092
          - 32093
        externalIPs:
          - 34.47.88.194
          - 34.47.88.194
    controller:
      service:
        type: NodePort
        nodePorts:
          - 32094
        externalIPs:
          - 34.47.88.194
  listeners:
    client:
      protocol: PLAINTEXT
      sasl:
        enabled: false
    internal:
      protocol: PLAINTEXT
      name: INTERNAL
    external:
      protocol: PLAINTEXT
      name: EXTERNAL
  advertisedListeners:
    - EXTERNAL://34.47.88.194:32092
    - EXTERNAL://34.47.88.194:32093
kafka-ui:
  env:
    - name: KAFKA_CLUSTERS_0_NAME
      value: "Development Kafka"
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: "kafka-dev-broker-headless:9092"
  service:
    type: NodePort
    port: 8080
    nodePort: 30000
